spring:
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}